### ISSUE TITLE
Diagram

### ISSUE THREAD

**Issue by floer32** [Yimeng-Zhang/feature-engineering-and-feature-selection#1]
I think the triangle diagram in this repo was from [Dive into Machine Learning](https://github.com/dive-into-machine-learning/dive-into-machine-learning), which was licensed under [Creative Commons Attribution 4.0 License](https://creativecommons.org/licenses/by/4.0/).  If you wouldn't mind updating, to include attribution to the source material, such as a link to the original doc, I think that would be helpful, because then people could find more related resources.

Note this is just in the interest of sharing resources openly with people. If they have a link back to the source of this diagram, then they can easily discover related helpful material.

**Comment by floer32** [comment]
This repo is great work by the way!! Thanks so much for sharing it publicly on GitHub.

**Comment by Yimeng-Zhang** [comment]
Thank you for the feedback. Will add it in a few moments.
